language: csharp  
sudo: required  
dist: trusty  
dotnet: 1.0.0-preview2-003121
env:  
  - DOTNETCORE=1
mono: 
  - none
os:  
  - linux
  - osx
osx_image: xcode8  
# whitelist
branches:
  only:
    - master
    - configure-travis  
before_install:  
  - chmod +x build.sh
script:  
  - ./build.sh